DROP TABLE user IF EXISTS;
create table user (
    user_no bigint generated by default as identity,
    login_id varchar(255) not null,
    password varchar(255) not null,
    name varchar(255) not null,
    gender varchar(20) not null,
    is_deleted smallint not null,
    updated_date timestamp,
    created_date timestamp,
    primary key (user_no)
  );
